app/auth.py
from flask import render_template, request, redirect, url_for, flash, session, Blueprint
from flask_login import login_required, current_user, login_user, logout_user, LoginManager
from functools import wraps

from app import app, db
from .models import User
from query import queries

bp = Blueprint('auth', __name__, url_prefix='/auth')


def init_login_manage(app):
    login_manager = LoginManager()

    login_manager.init_app(app)

    login_manager.login_view = 'index'
    login_manager.login_message = 'Доступ к данной странице есть только у авторизованных пользователей'
    login_manager.login_message_category = 'warning'

    login_manager.user_loader(load_user)


def load_user(user_id):
    try:
        with db.connect().cursor(named_tuple=True) as cursor:
            query = 'SELECT * FROM Users WHERE UserID=%s'
            cursor.execute(query, (user_id,))
            user_data = cursor.fetchone()
            print(user_data)
            if user_data:
                return User(user_data.UserID, user_data.Login, user_data.RoleID)
    except:
        db.connect().rollback()
        print("ошибка при загрузки пользователя")
    return None


def checkRole(action):
    def decorator(f):
        @wraps(f)
        def wrapper(*args, **kwargs):
            user_id = kwargs.get('user_id')
            user = None
            print(user_id)
            if user_id:
                user = load_user(user_id)
            if current_user.can(action,record=user):
                return f(*args, **kwargs)
            flash("У вас недостаточно прав для выполнения данного действия", "danger")
            return redirect(url_for("index"))
        return wrapper
    return decorator


@bp.route('/login', methods=['GET', 'POST'])
def login():
    user_data = {}
    if request.method == "POST":
        login = request.form.get("login")
        password = request.form.get("password")
        remember = request.form.get("remember")

        user_data['login'] = login
        user_data['password'] = password
        user_data['remember'] = remember
        try:
            with db.connect().cursor(named_tuple=True) as cursor:
                query = 'SELECT * FROM Users WHERE Login=%s AND PasswordHash=SHA2(%s,256)'
                print("я тут")
                cursor.execute(query, (login, password))
                print("я тут")
                user_data = cursor.fetchone()
                print("я тут")
                print(user_data)
                if user_data:
                    print("вот данные", user_data)
                    user = User(user_data.UserID, user_data.Login, user_data.RoleID)
                    print("я тут")
                    login_user(user, remember=remember)
                    print("я тут")
                    flash('Вы успешно прошли аутентификацию', 'success')
                    return redirect(url_for('index'))
                else:
                    flash('Неверные логин или пароль', 'danger')
        except:
            db.connect().rollback()
            print("ошибка при авторизации")

    return render_template('login.html', user=user_data)

@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/alerts.css') }}">
    {% block header_links %}

    {% endblock %}
    <title>bot</title>
</head>

<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-..."></script>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">Bot</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon" id="navbarButton"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto">
                        {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link">{{ current_user.login }}</a>
                        </li>
                        {% if current_user.role_id == 3 %}
                        <li class="nav-item">
                            <a class="nav-link {%if request.endpoint == 'logout'%}active{% endif%}" aria-current="page"
                                href="{{url_for('user.user_reviews')}}">Ваши отзывы</a>
                        </li>
                        {% endif %}
                        {% if current_user.role_id == 1 or current_user.role_id == 2 %}
                        <li class="nav-item">
                            <a class="nav-link {%if request.endpoint == 'logout'%}active{% endif%}" aria-current="page"
                                href="{{url_for('admin.moderation_reviews')}}">модерация отзывов</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link {%if request.endpoint == 'logout'%}active{% endif%}" aria-current="page"
                                href="{{url_for('auth.logout')}}">Выход</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link {%if request.endpoint == 'login'%}active{% endif%}" aria-current="page"
                                href="{{url_for('auth.login')}}">Вход</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="container">
            {% block content %}
            <p> пусто </p>
            {% endblock %}
        </div>
        <alerts>
            <div class="container">
                <div id="alert-container" class="alert-container">
                    {% if request.endpoint != 'login' %}
                    {% with msg = get_flashed_messages(with_categories=true) %}
                    {% for category, message in msg %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        <div class="toast-duration"></div> <!-- Элемент для отображения времени -->
                    </div>
                    {% endfor %}
                    {% endwith %}
                    {% endif %}
                </div>
            </div>
        </alerts>
    </main>
    <footer class="bg-body-tertiary text-center text-lg-start fixed-bottom">
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">

            <a class="text-body">©Кирияк Юрий Анатольевич группа 221-331</a>
        </div>
        <!-- Copyright -->
    </footer>
    {% block modal_windows %}
    {% endblock %}
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    {% block script_link %}

    {% endblock %}
</body>

</html>

app/templates/card.html
{% macro BotCard(card, current_user) %}
<div class="flip">
    <div class="front">
        <div class="mdc-card bottom-card mdc-elevation--z4">
            <div class="first-half">
                <div class="mdc-card__primary-action media-image top-card mdc-elevation--z8">
                    <div class="mdc-card__media mdc-card__media--square">
                        <div class="mdc-card__media-content">
                            {% if card.FileID == None %}
                            <img class="image-box"
                                src="https://sun1-25.userapi.com/impg/Nsh6LClv4iO6uL7KBYiKuGIuuZm-yVrIeIhrAQ/Si37BnM4vhM.jpg?size=736x736&quality=96&sign=86d57af06fc6528a5736fec9b06ab2f2&type=album">
                            {% else %}
                            <img class="image-box" src="{{ url_for('uploaded_file', file_image_id=card.FileID ) }}"
                                alt="{{ card.NameBot }}">
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="last-half">
                <div class="card-info">
                    <div class="d-flex flex-column">
                        <h2 class="text-warning">{{ card.NameBot }}</h2>
                        <h1></h1>
                        <div class="pb-3" style="min-height: 55px;">
                            {% if card.BotTypes %}
                            {% set types = card.BotTypes.split(',') %}
                            {% for type in types %}
                            <span class="badge bg-secondary bg-success m-1">{{ type }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                        {% if card.AverageRating != None%}
                        <div class="d-flex">
                            <h6><span class="yellow-star">&#9733;</span>{{ card.AverageRating}} &#183;</h6>
                            <h6 class="ps-1">{{ card.ReviewCount }} отзывов</h6>
                        </div>
                        <div class="d-flex flex-row-reverse">
                            <p>{{ card.ReleaseDate }}</h6>
                        </div>
                        {% else %}
                        <div class="d-flex">
                            <h6><span class="yellow-star">&#9733;</span>0 &#183;</h6>
                            <h6 class="ps-1">отзывов нет</h6>
                        </div>
                        <div class="d-flex flex-row-reverse">
                            <p>{{ card.ReleaseDate }}</h6>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="back">
        <div class="mdc-card bottom-card mdc-elevation--z4">
            <div class="first-half">
                <div class="d-flex">
                    <a type="button" class="m-1 btn btn-secondary"
                        href="{{url_for('show_card', card_id = card.BotID)}}">Просмотр</a>
                    {% if current_user.role_id == 1 or current_user.role_id == 2%}
                    <a type="button" class="m-1 btn btn-primary"
                        href="{{url_for('admin.edit_bot', bot_id = card.BotID)}}">Редактировать</a>
                    {% endif %}
                    {% if current_user.role_id == 1 %}
                    <button type="button" class="m-1 btn btn-danger" data-action={{url_for('admin.delete_bot',
                        bot_id=card.BotID)}} data-bs-toggle="modal" data-bs-target="#deleteBot">Удалить</button>
                    {% endif %}
                </div>
            </div>

        </div>
    </div>
</div>

{% endmacro %}

app/templates/create_bot.html
{% extends 'base.html' %}

{% block content %}
{% from 'form_card.html' import form %}

{{ form(types, card)}}
{% endblock%}

app/templates/edit_bot.html
{% extends 'base.html' %}

{% block content %}
{% from 'form_card.html' import form %}

{{ form(types, card)}}

{% endblock %}

app/templates/form_card.html
{% macro form(types, card) %}
{% if request.endpoint == "admin.edit_bot" %}
    <h1 class='mb-3'>Редактирование бота</h1>
{% elif request.endpoint == "admin.create_bot" %}
    <h1 class='mb-3'>Создание бота</h1>
{% endif %}
<form method="POST" enctype="multipart/form-data">
    <div class="mb-3">
        <label for="InputName" class="form-label">Имя</label>
        <input type="text" name='NameBot' class="form-control" id="InputName" value="{{ card.NameBot or '' }}">
    </div>
    <div class="mb-3">
        <label for="InputNameForWhat" class="form-label">Для чего этот бот?</label>
        <input type="text" name='NameForWhat' class="form-control" id="InputNameForWhat" value="{{ card.NameForWhat or '' }}">
    </div>
    <div class="mb-3">
        <label for="types" class="form-label">Выберите типы (можно выбрать несколько, удерживая Ctrl)</label>
        <select id="types" name="types" class="form-select" multiple aria-label="Multiple select example">
            {% for type in types %}
                <option value="{{ type.TypeName }}" {% if type.TypeName in card.types %} selected {% endif %}>{{ type.TypeName }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="mb-3">
        <label for="InputShortDescription" class="form-label">Краткое описание</label>
        <input type="text" name='ShortDescription' class="form-control" id="InputShortDescription" value="{{ card.ShortDescription or '' }}">
    </div>
    <div class="mb-3">
        <label for="InputDescription" class="form-label">Описание</label>
        <input type="text" name='Description' class="form-control" id="InputDescription" value="{{ card.Description or '' }}">
    </div>
    <div class="mb-3">
        <label for="InputDeveloper" class="form-label">Разработчик</label>
        <input type="text" name='Developer' class="form-control" id="InputDeveloper" value="{{ card.Developer or '' }}">
    </div>
    <div class="mb-3">
        <label for="InputCover" class="form-label">фотография бота</label>
        <input type="file" name="CoverImage" class="form-control" id="InputCover">
    </div>
    <button type="submit" class="btn btn-primary">Отправить</button>
</form>
{% endmacro %}

app/templates/index.html
{% extends 'base.html' %}

{% block header_links %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/card.css') }}">
{% endblock %}

{% block content %}

<div class="container mt-5 pt-5">
    {% for card in cards %}
    {% from 'card.html' import BotCard %}

    {{ BotCard(card, current_user)}}
    {% endfor %}
</div>
<div
    class="d-flex {% if current_user.role_id == 1 %}justify-content-between{% else %}justify-content-end{% endif %} p-3">
    {% if current_user.role_id == 1 %}
    <a class="btn btn-success" style="height: 100%;" href="{{url_for('admin.create_bot')}}">создать бота</a>
    {% endif %}
    <nav aria-label="Page navigation example" class="text-end">
        <ul class="pagination">
            <li class="page-item {% if page == 1 %}disabled{% endif %}">
                <a class="page-link" href="?page={{ page - 1 }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% for num_page in range(1, total_pages + 1) %}
            <li class="page-item {% if page == num_page %}active{% endif %}">
                <a class="page-link" href="?page={{ num_page }}">{{ num_page }}</a>
            </li>
            {% endfor %}
            <li class="page-item {% if page == total_pages %}disabled{% endif %}">
                <a class="page-link" href="?page={{ page + 1 }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

{% block modal_windows %}
<div class="modal fade" id="deleteBot" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Удаление записи</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Вы действительно хотите удалить бота <span class="name-bot"><span>?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Нет</button>
                <form class="modal-form" method="post">
                    <button type="submit" class="btn btn-primary">Да</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script_link %}
<script src="{{ url_for('static', filename='js/card.js') }}"></script>
<script src="{{ url_for('static', filename='js/delete_bot.js') }}"></script>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-md-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">вход</h5>
                </div>
                <div class="card-body">
                    {% if errors %}
                    <div id="alert-container-login" class="alert-container-login">
                        {% for error in errors %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ error }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <form method="POST" action="{{ url_for('auth.login') }}">
                        <div class="mb-3">
                            <label for="InputLogin" class="form-label">Логин</label>
                            <input type="text" name="login" class="form-control" id="InputLogin"
                                value="{{ request.form.login or '' }}">
                        </div>
                        <div class="mb-3">
                            <label for="InputPassword" class="form-label">Пароль</label>
                            <input type="password" name="password" class="form-control" id="InputPassword"
                                value="{{ request.form.password or '' }}">
                        </div>
                        <div class="mb-3 form-check">
                            <input type="checkbox" class="form-check-input" name="remember" id="rememberMeCheck"
                                {% if request.form.get('remember') %}checked{% endif %}>
                            <label class="form-check-label" for="rememberMeCheck">Запомнить меня</label>
                        </div>
                        <button type="submit" class="btn btn-primary">Войти</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/modal_windows.html
{% macro login_form(user, errors) %}

<div class="modal {% if session['login_error'] == False %}fade{% endif %}" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel">Аутентификация пользователей</h5>
                <a class="btn-close" aria-current="page" href="{{url_for('index')}}"></a>

            </div>
            <div class="modal-body">
                <form method="POST" action="{{ url_for('auth.login') }}">
                    <div class="mb-3">
                        <label for="InputLogin" class="form-label">Логин</label >
                        <input type="text" name="login" class="form-control" id="InputLogin" value={{ request.form.login or ''}}>
                    </div>
                    <div class="mb-3">
                        <label for="InputPassword" class="form-label">Пароль</label>
                        <input type="password" name="password" class="form-control" id="InputPassword" value={{ request.form.password or ''}}>
                    </div>
                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" name="remember" id="rememberMeCheck" {% if request.form.get('remember') %}checked{% endif %}>
                        <label class="form-check-label" for="rememberMeCheck" >Запомнить меня</label>
                    </div>
                    <button type="submit" class="btn btn-primary">Войти</button>
                </form>
            </div>
        </div>
        <div id="alert-container-login" class="alert-container-login">
            {% with msg = get_flashed_messages(with_categories=true) %}
                {% for category, message in msg %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        <div class="toast-duration"></div>
                    </div>
                {% endfor %}
            {% endwith %}
        </div>
    </div>
</div>


{% endmacro %}

app/templates/moder_reviews.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5 pt-5">
    <h1 class="text-center mb-4">Не рассмотренные отзывы</h1>
        <table class="table table-dark table-striped">
            <thead>
                <tr>
                    <th scope="col">Имя бота</th>
                    <th scope="col">Рейтинг</th>
                    <th scope="col" >Текст</th>
                    <th scope="col" class="text-center">Действия</th>
                </tr>
            </thead>
            <tbody>
                {% for review in reviews_moder %}
                <tr>
                    <td>{{ review.NameBot }}</td>
                    <td>{{ review.Rating }}</td>
                    <td>{{ review.TextReviews | safe }}</td>
                    <td class="text-center">
                        <a class="btn btn-primary btn-sm"
                            href="{{ url_for('admin.show_reviews', id_review=review.ReviewID) }}">Модерировать</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
</div>

{% endblock %}

app/templates/secret.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>секретная страница</p>
</body>
</html>

app/templates/show_card.html
{% extends 'base.html' %}

{% block header_links %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" href="{{ url_for('static', filename='css/card.css') }}">
<style>
    body {
        background-color: #f8f9fa;
    }
</style>
{% endblock %}

{% block content %}
<!-- описание бота -->
<div class="container my-5 mt-5 py-5">
    <div class="row">
        <div class="col-md-6">
            <div class="product-info">
                <h2 class="text-decoration-underline">{{ bot.NameBot }}</h2>
                <div class="ratings">
                    {% if bot.AverageRating is not none %}
                    <p>Средняя оценка: {{ bot.AverageRating }} &nbsp;&nbsp; Отзывов: {{ bot.ReviewCount }}</p>
                    {% else %}
                    <p>Отзывов пока нет, вы можете стать первым!</p>
                    {% endif %}
                </div>
                {% if bot.ShortDescription != '' %}
                <p class="description fw-bold">{{ bot.ShortDescription | safe }}</p>
                {% endif %}
                {% if bot.Description != None %}
                <div style="min-height: 300px;">
                    <p class="description">Описание:</p>
                    <p class="description">{{ bot.Description | safe }}</p>
                </div>
                {% else %}
                <div style="min-height: 200px;">
                    <p class="description">Описания пока нет.</p>
                </div>
                {% endif %}
                <p class="description text-muted text-end">{{ bot.ReleaseDate }}</p>
            </div>
        </div>
        <div class="col-md-6 d-flex align-items-center justify-content-center">
            <div class="product-image-container">
                {% if bot.FileImageID == None %}
                <img class="image-box"
                    src="https://sun1-25.userapi.com/impg/Nsh6LClv4iO6uL7KBYiKuGIuuZm-yVrIeIhrAQ/Si37BnM4vhM.jpg?size=736x736&quality=96&sign=86d57af06fc6528a5736fec9b06ab2f2&type=album">
                {% else %}
                <img class="image-box" src="{{ url_for('uploaded_file', file_image_id=bot.FileImageID ) }}"
                    alt="{{ bot.NameBot }}">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- Форма для добавления отзыва -->
{% if not review_user and current_user.is_authenticated == True %}
<form method="POST" action="{{ url_for('write_review', bot_id=bot.BotID, user_id=current_user.id) }}">
    <div class="container my-5">
        <div class="row justify-content-end">
            <div class="col-md-6">
                <h2>Оставить свой отзыв</h2>
                <form>
                    <div class="mb-3 stars">
                        <input class="star star-5" id="star-5" type="radio" name="5" />
                        <label class="star star-5" for="star-5"></label>
                        <input class="star star-4" id="star-4" type="radio" name="4" />
                        <label class="star star-4" for="star-4"></label>
                        <input class="star star-3" id="star-3" type="radio" name="3" />
                        <label class="star star-3" for="star-3"></label>
                        <input class="star star-2" id="star-2" type="radio" name="2" />
                        <label class="star star-2" for="star-2"></label>
                        <input class="star star-1" id="star-1" type="radio" name="1" />
                        <label class="star star-1" for="star-1"></label>
                    </div>
                    <div class="mb-3">
                        <textarea class="form-control" style="height: 250px;" id="userReview" name="userReview" rows="3"
                            required></textarea>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">Отправить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</form>
{% elif current_user.is_authenticated == True %}
<div class="row justify-content-end">
    <div class="col-md-6 ">
        <h1>Ваш отзыв {% if review_user.StatusID == 1 %}еще не еще расмотрен{% elif review_user.StatusID ==
            3%}отклонен{% endif %}</h1>
        <div class="card mt-3">
            <div class="card-body">
                <h5 class="card-title">{{ review_user.Login }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ review_user.PublicationDate }}</h6>
                {% if review_user.Rating == 5 %}
                <p class="card-text">⭐⭐⭐⭐⭐</p>
                {% elif review_user.Rating == 4 %}
                <p class="card-text">⭐⭐⭐⭐</p>
                {% elif review_user.Rating == 3 %}
                <p class="card-text">⭐⭐⭐</p>
                {% elif review_user.Rating == 2 %}
                <p class="card-text">⭐⭐</p>
                {% elif review_user.Rating == 1 %}
                <p class="card-text">⭐</p>
                {% endif %}
                <p class="card-text">{{ review_user.TextReviews | safe}}</p>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% if reviews %}
<!-- Таблица всх отзывов-->
<div class="row justify-content-center">
    <div class="col-md-8 ">
        <h2>Отзывы</h2>
        <div class="container mt-5">
            {% for review in reviews %}
            <div class="card mt-3">
                <div class="card-body">
                    <h5 class="card-title">{{ review.Login }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ review.PublicationDate }}</h6>
                    {% if review.Rating == 5 %}
                    <p class="card-text">⭐⭐⭐⭐⭐</p>
                    {% elif review.Rating == 4 %}
                    <p class="card-text">⭐⭐⭐⭐</p>
                    {% elif review.Rating == 3 %}
                    <p class="card-text">⭐⭐⭐</p>
                    {% elif review.Rating == 2 %}
                    <p class="card-text">⭐⭐</p>
                    {% elif review.Rating == 1 %}
                    <p class="card-text">⭐</p>
                    {% endif %}
                    <p class="card-text">{{ review.TextReviews | safe}}</p>
                </div>
            </div>
            {% endfor%}
        </div>
    </div>
</div>

<!-- Пагинация -->
<div class="row justify-content-center pt-3 pb-3">
    <div class="col-md-8 ">
        <nav aria-label="Page navigation example" class="text-end">
            <ul class="pagination justify-content-center">
                <li class="page-item {% if page == 1 %}disabled{% endif %}">
                    <a class="page-link" href="?page={{ page - 1 }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% for num_page in range(1, total_pages + 1) %}
                <li class="page-item {% if page == num_page %}active{% endif %}">
                    <a class="page-link" href="?page={{ num_page }}">{{ num_page }}</a>
                </li>
                {% endfor %}
                <li class="page-item {% if page == total_pages %}disabled{% endif %}">
                    <a class="page-link" href="?page={{ page + 1 }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>
{% endif %}
{% endblock %}

app/templates/show_reviews.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card mt-4">
                <div class="card-body">
                    <h5 class="card-title">Логин: {{ review.Login }}</h5>
                    <p class="card-text">Оценка: {{ review.Rating }}</p>
                    <p class="card-text">Текст отзыва: {{ review.TextReviews | safe }}</p>
                    <p class="card-text">Отзыв на: {{ review.NameBot }}</p>
                    <p class="card-text">Отзыв отправлен: {{ review.PublicationDate }}</p>

                    <div class="d-flex mt-4">
                        <form action="{{ url_for('admin.approval', id_review=review.ReviewID) }}" method="post">
                            <button type="submit" class="btn btn-success">Одобрить</button>
                        </form>
                        <form action="{{ url_for('admin.reject', id_review=review.ReviewID) }}" method="post">
                            <button type="submit" class="btn btn-danger ms-3">Отклонить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}